### ISSUE TITLE
Suggested Copilot text is same color as existing text

### ISSUE THREAD

**Issue by JosephTLyons** [mauscoelho/zed-mau-themes#1]
In this screenshot, everything before the cursor is existing text and everything after is an inline suggestion from Copilot. An improvement here would be to change the color of the suggestion to make it easier to differentiate between the two.

<img width="573" alt="SCR-20240716-monh" src="https://github.com/user-attachments/assets/2a911d97-1b9e-480a-a7c8-bb93fb3be961">

**Comment by mauscoelho** [comment]
Thanks for the suggestion @JosephTLyons
